### ISSUE TITLE
One issue

### ISSUE THREAD

**Issue by BX-xb** [keyu07/DADG#1]
Hi, I have two questions. 
1.When I load the pretrain AlexNet,  this file (alexnet_caffe.pth) is corrupted and cannot be decompressed.
2.What is the version of pytorch and torchvision?

**Comment by Epi-NMT** [comment]
Thanks for your interest.
1. You can just download it and put it in the folder, no need to decompress.
2. Torch version 1.4.0 and torchvision 0.5.0.

**Comment by BX-xb** [comment]
Thank you for your help!
